# Generated by Django 2.2.4 on 2019-10-14 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Field name')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'db_table': 'ddt_fields',
                'ordering': ['content_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='Object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content Type')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_database_translation.Field', verbose_name='Field')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'ddt_items',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('iso2', models.CharField(max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='ISO2')),
                ('iso3', models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='ISO3')),
                ('django_language_name', models.CharField(help_text="Should match a value from settings.LANGUAGES, such as 'fr-FR' or 'en-US'", max_length=5, unique=True, verbose_name='Django language name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'ddt_languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Translated text')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_database_translation.Item', verbose_name='Item')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_database_translation.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'db_table': 'ddt_translations',
                'ordering': [],
            },
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['item', 'language'], name='idx_item_lang'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('language', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('field', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('content_type', 'name')},
        ),
    ]
